import{loadProfile,saveProfile,loadStats,recordResult,resetStats,renderProfile,renderStats}from"./profile.js";
import{loadPreferences,savePreferences,applyPreferences}from"./themes.js";
import{ConnectGame,renderBoard,renderMatch}from"./game.js";import{chooseMove}from"./ai.js";import{OnlineRoom}from"./online.js";
import{loginGoogle,loginEmail,registerEmail,ensureAuth}from"./firebase.js";import{showScreen,setOnlineTab,buildColumnControls,setGameStatus,showWinner,hideWinner}from"./ui.js";
import{playSound,launchConfetti}from"./effects.js";import{emptyBoard,formatTime,showToast}from"./utils.js";
let profile=loadProfile(),preferences=loadPreferences(),mode="",difficulty="medium",scores={R:0,Y:0},recordedRound=null,overlayRound=null;
applyPreferences(preferences);renderProfile(profile);renderStats(loadStats());
const game=new ConnectGame(g=>{renderBoard(g);renderMatch(g,scores);updateTurn()},finishLocal);
const online=new OnlineRoom({onRoom:renderOnline,onMessages:renderMessages,onMissing:()=>{showToast("Room no longer exists.");showScreen("home")}});
buildColumnControls(handleColumn);ensureAuth().catch(console.error);
function handleColumn(c){if(mode==="online"){online.move(c).catch(e=>setGameStatus(e.message));return}if(mode==="spectator"){setGameStatus("You are watching this match.");return}if(mode==="single"&&game.currentPiece==="Y")return;const r=game.playColumn(c);if(!r.ok){setGameStatus(r.reason==="full"?"That column is full.":"The round is finished.");playSound("error",preferences.sound);return}playSound("move",preferences.sound);if(mode==="single"&&!game.finished&&game.currentPiece==="Y"){setGameStatus("Computer is thinking…");setTimeout(()=>{game.playColumn(chooseMove(game.board,difficulty));playSound("move",preferences.sound);setGameStatus("")},difficulty==="hard"?450:320)}}
function startSingle(){mode="single";scores={R:0,Y:0};game.configure({mode,player1:profile.name,player2:`${difficulty[0].toUpperCase()}${difficulty.slice(1)} AI`,colors:{R:profile.color,Y:"#ffd83d"}});prepare("SINGLE")}
function startLocal(){mode="local";scores={R:0,Y:0};game.configure({mode,player1:profile.name,player2:localPlayer2Name.value.trim()||"Player 2",colors:{R:localColor1.value,Y:localColor2.value}});prepare("LOCAL")}
function prepare(label){modeBadge.textContent=label;roomInfo.textContent="";chatPanel.classList.add("hidden");readyButton.classList.add("hidden");newRoundButton.classList.remove("hidden");setGameStatus("");hideWinner();renderBoard(game);renderMatch(game,scores);updateTurn();showScreen("game")}
function updateTurn(){if(["online","spectator"].includes(mode))return;turnMessage.textContent=game.finished?"Round finished":`${game.currentPiece==="R"?game.player1:game.player2}'s turn`}
function finishLocal(r){if(r.type==="win"){const n=r.piece==="R"?game.player1:game.player2;scores[r.piece]++;recordResult(r.piece==="R"?"win":"loss");renderMatch(game,scores);showWinner(`${n} Wins!`,"Start a new round whenever you are ready.");launchConfetti();playSound("win",preferences.sound)}else{recordResult("draw");showWinner("Draw Game","Start another round whenever you are ready.")}renderStats(loadStats())}
function renderOnline(room,role){mode=role==="spectator"?"spectator":"online";const p1=room.player1||{name:"Player 1",color:"#ff3158"},p2=room.player2||{name:"Waiting…",color:"#ffd83d"};Object.assign(game,{mode,player1:p1.name,player2:p2.name,colors:{R:p1.color,Y:p2.color},board:room.board||emptyBoard(),currentPiece:room.turn,finished:room.finished,winning:room.winning||[]});renderBoard(game);renderMatch(game,room.scores||{R:0,Y:0});modeBadge.textContent=role==="spectator"?"WATCHING":"ONLINE";roomInfo.textContent=`Room ${online.code}`;chatPanel.classList.remove("hidden");spectatorCount.textContent=`${Math.max(0,room.spectatorCount||0)} watching`;newRoundButton.classList.add("hidden");const mine=role==="host"?"R":role==="guest"?"Y":"";
if(room.status==="waiting"){lobbyRoomCode.textContent=online.code;lobbyStatus.textContent="Waiting for your opponent to join.";turnMessage.textContent="Waiting for Player 2…";showScreen("lobby");return}
showScreen("game");if(room.finished){const title=room.winner==="draw"?"Draw Game":`${room.winner==="R"?p1.name:p2.name} Wins!`;turnMessage.textContent=title;readyButton.classList.toggle("hidden",role==="spectator");if(role!=="spectator"){const ready=role==="host"?room.readyHost:room.readyGuest;readyButton.textContent=ready?"Ready — Waiting for Opponent":"Ready for Next Round";readyButton.disabled=ready}if(overlayRound!==room.round){overlayRound=room.round;showWinner(title,role==="spectator"?"Both players can start another round when ready.":"Both players must press Ready for the next round.");if(room.winner!=="draw"){launchConfetti();playSound("win",preferences.sound)}}if(role!=="spectator"&&recordedRound!==room.round){recordedRound=room.round;recordResult(room.winner==="draw"?"draw":room.winner===mine?"win":"loss");renderStats(loadStats())}}else{hideWinner();readyButton.classList.add("hidden");const n=room.turn==="R"?p1.name:p2.name;turnMessage.textContent=role==="spectator"?`${n}'s turn`:room.turn===mine?"Your turn":`${n}'s turn`}updatePresence(room)}
function updatePresence(room){const now=Date.now(),s=p=>{if(!p?.lastSeen)return"Offline";const d=p.lastSeen.toDate?p.lastSeen.toDate():new Date(p.lastSeen);return now-d.getTime()<300000?"Online":"Disconnected"};player1Status.textContent=s(room.player1);player2Status.textContent=room.player2?s(room.player2):"Waiting"}
function renderMessages(ms){messagesList.innerHTML="";ms.forEach(m=>{const d=document.createElement("div");d.className="chat-message";const h=document.createElement("strong"),p=document.createElement("p");h.textContent=`${m.name||"Player"} · ${formatTime(m.createdAt)}`;p.textContent=m.text;d.append(h,p);messagesList.appendChild(d)});messagesList.scrollTop=messagesList.scrollHeight}
async function leave(){if(["online","spectator"].includes(mode))await online.leave();mode="";hideWinner();showScreen("home")}
singlePlayerButton.onclick=()=>{setupTitle.textContent="Single Player";singleSetup.classList.remove("hidden");localSetup.classList.add("hidden");startSetupGameButton.dataset.mode="single";showScreen("setup")};
localButton.onclick=()=>{setupTitle.textContent="Local Multiplayer";singleSetup.classList.add("hidden");localSetup.classList.remove("hidden");localColor1.value=profile.color;startSetupGameButton.dataset.mode="local";showScreen("setup")};
document.querySelectorAll("[data-difficulty]").forEach(b=>b.onclick=()=>{difficulty=b.dataset.difficulty;document.querySelectorAll("[data-difficulty]").forEach(x=>x.classList.toggle("selected",x===b))});
startSetupGameButton.onclick=e=>e.currentTarget.dataset.mode==="single"?startSingle():startLocal();onlineButton.onclick=()=>showScreen("online");tutorialButton.onclick=()=>tutorialDialog.showModal();cancelSetupButton.onclick=onlineBackButton.onclick=()=>showScreen("home");homeButton.onclick=leave;leaveGameButton.onclick=leave;
document.querySelectorAll("[data-online-tab]").forEach(b=>b.onclick=()=>setOnlineTab(b.dataset.onlineTab));
createRoomButton.onclick=async()=>{try{onlineStatus.textContent="Creating room…";const c=await online.create(profile);lobbyRoomCode.textContent=c;showScreen("lobby")}catch(e){onlineStatus.textContent=e.message}};
joinRoomButton.onclick=async()=>{try{await online.join(joinCodeInput.value,profile)}catch(e){onlineStatus.textContent=e.message}};
spectateRoomButton.onclick=async()=>{try{await online.spectate(spectateCodeInput.value)}catch(e){onlineStatus.textContent=e.message}};
copyCodeButton.onclick=()=>navigator.clipboard.writeText(online.code).then(()=>showToast("Room code copied."));copyInviteButton.onclick=()=>navigator.clipboard.writeText(online.inviteLink()).then(()=>showToast("Invite link copied."));
whatsAppButton.onclick=()=>open(`https://wa.me/?text=${encodeURIComponent(`Play Connect4 with me! Room ${online.code}: ${online.inviteLink()}`)}`,"_blank");leaveLobbyButton.onclick=leave;
newRoundButton.onclick=()=>{hideWinner();game.reset()};readyButton.onclick=()=>online.ready().catch(e=>setGameStatus(e.message));closeWinnerOverlay.onclick=hideWinner;
chatForm.onsubmit=e=>{e.preventDefault();online.sendMessage(chatInput.value).then(()=>chatInput.value="").catch(e=>showToast(e.message))};document.querySelectorAll("[data-reaction]").forEach(b=>b.onclick=()=>online.sendMessage(b.dataset.reaction,"reaction"));
editProfileButton.onclick=()=>{profileNameInput.value=profile.name;profileColorInput.value=profile.color;profileDialog.showModal()};saveProfileButton.onclick=()=>{profile=saveProfile({...profile,name:profileNameInput.value,color:profileColorInput.value});renderProfile(profile);profileDialog.close();showToast("Profile saved.")};
showEmailLoginButton.onclick=()=>emailAccountFields.classList.toggle("hidden");googleLoginButton.onclick=async()=>{try{const r=await loginGoogle();accountStatus.textContent=`Connected as ${r.user.email||"Google user"}.`}catch(e){accountStatus.textContent=e.message}};
emailRegisterButton.onclick=()=>emailAction("register");emailSignInButton.onclick=()=>emailAction("login");async function emailAction(a){try{const r=a==="register"?await registerEmail(emailInput.value,passwordInput.value):await loginEmail(emailInput.value,passwordInput.value);accountStatus.textContent=`Connected as ${r.user.email}.`}catch(e){accountStatus.textContent=e.message}}
settingsButton.onclick=()=>{themeSelect.value=preferences.theme;soundToggle.checked=preferences.sound;customThemeControls.classList.toggle("hidden",preferences.theme!=="custom");customBackground.value=preferences.custom.background;customPanel.value=preferences.custom.panel;customBoard.value=preferences.custom.board;customButton.value=preferences.custom.button;customText.value=preferences.custom.text;customAccent.value=preferences.custom.accent;settingsDialog.showModal()};
themeSelect.onchange=e=>customThemeControls.classList.toggle("hidden",e.target.value!=="custom");saveSettingsButton.onclick=()=>{preferences={theme:themeSelect.value,sound:soundToggle.checked,custom:{background:customBackground.value,panel:customPanel.value,board:customBoard.value,button:customButton.value,text:customText.value,accent:customAccent.value}};savePreferences(preferences);settingsDialog.close();showToast("Settings saved.")};
resetStatsButton.onclick=()=>{if(confirm("Reset all saved statistics on this device?"))renderStats(resetStats())};
const params=new URLSearchParams(location.search),shared=params.get("room");if(shared){joinCodeInput.value=shared;spectateCodeInput.value=shared;setOnlineTab("join");showScreen("online")}else online.restore().catch(console.error);
