import{db,ensureAuth,doc,getDoc,setDoc,updateDoc,deleteDoc,onSnapshot,runTransaction,serverTimestamp,collection,addDoc,query,orderBy,limit,increment}from"./firebase.js";
import{emptyBoard,findOpenIndex,winningIndexes,isBoardFull,randomCode,sanitizeName}from"./utils.js";import{SITE_URL}from"./config.js";const KEY="connect4_online_session_v3";
export class OnlineRoom{constructor(cb){this.cb=cb;this.code="";this.role="";this.room=null;this.unsubs=[];this.heartbeat=null}
async create(profile){const u=await ensureAuth();let code="";for(let a=0;a<8;a++){const c=randomCode(),r=doc(db,"rooms",c);if(!(await getDoc(r)).exists()){code=c;break}}if(!code)throw Error("Could not generate a room code.");await setDoc(doc(db,"rooms",code),{hostUid:u.uid,guestUid:null,status:"waiting",board:emptyBoard(),turn:"R",round:1,winner:"",winning:[],finished:false,readyHost:false,readyGuest:false,scores:{R:0,Y:0},player1:playerData(u.uid,profile),player2:null,spectatorCount:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});this.start(code,"host");return code}
async join(code,profile){const u=await ensureAuth();code=clean(code);const r=doc(db,"rooms",code);await runTransaction(db,async t=>{const s=await t.get(r);if(!s.exists())throw Error("Room not found.");const d=s.data();if(d.guestUid&&d.guestUid!==u.uid)throw Error("Room is full.");t.update(r,{guestUid:u.uid,player2:playerData(u.uid,profile),status:"playing",updatedAt:serverTimestamp()})});this.start(code,"guest")}
async spectate(code){await ensureAuth();code=clean(code);const r=doc(db,"rooms",code);if(!(await getDoc(r)).exists())throw Error("Room not found.");await updateDoc(r,{spectatorCount:increment(1)});this.start(code,"spectator")}
start(code,role){this.stop(false);this.code=code;this.role=role;localStorage.setItem(KEY,JSON.stringify({code,role}));const r=doc(db,"rooms",code);this.unsubs.push(onSnapshot(r,s=>{if(!s.exists()){this.cb.onMissing?.();this.stop();return}this.room={id:s.id,...s.data()};this.cb.onRoom?.(this.room,this.role)}));const q=query(collection(db,"rooms",code,"messages"),orderBy("createdAt","asc"),limit(80));this.unsubs.push(onSnapshot(q,s=>this.cb.onMessages?.(s.docs.map(d=>({id:d.id,...d.data()})))));this.heartbeat=setInterval(()=>this.touchPresence(),25000);this.touchPresence()}
async restore(){const s=JSON.parse(localStorage.getItem(KEY)||"null");if(!s?.code)return false;if(!(await getDoc(doc(db,"rooms",s.code))).exists()){localStorage.removeItem(KEY);return false}this.start(s.code,s.role);return true}
async move(col){if(!["host","guest"].includes(this.role))throw Error("Spectators cannot play.");const u=await ensureAuth(),r=doc(db,"rooms",this.code);await runTransaction(db,async t=>{const s=await t.get(r);if(!s.exists())throw Error("Room ended.");const d=s.data(),piece=this.role==="host"?"R":"Y";if(d.status!=="playing"||d.finished)throw Error("Round is not active.");if(d.turn!==piece)throw Error("It is not your turn.");if((piece==="R"&&d.hostUid!==u.uid)||(piece==="Y"&&d.guestUid!==u.uid))throw Error("You are not a player.");const b=[...d.board],i=findOpenIndex(b,Number(col));if(i<0)throw Error("That column is full.");b[i]=piece;const w=winningIndexes(b,i,piece),draw=!w.length&&isBoardFull(b),up={board:b,updatedAt:serverTimestamp(),turn:piece==="R"?"Y":"R"};if(w.length||draw){up.finished=true;up.winner=w.length?piece:"draw";up.winning=w;up.readyHost=false;up.readyGuest=false;if(w.length)up[`scores.${piece}`]=increment(1)}t.update(r,up)})}
async ready(){if(!["host","guest"].includes(this.role))return;const r=doc(db,"rooms",this.code),field=this.role==="host"?"readyHost":"readyGuest";await runTransaction(db,async t=>{const s=await t.get(r);if(!s.exists())return;const d=s.data(),h=this.role==="host"?true:d.readyHost,g=this.role==="guest"?true:d.readyGuest;if(h&&g)t.update(r,{board:emptyBoard(),turn:d.round%2===1?"Y":"R",round:increment(1),winner:"",winning:[],finished:false,readyHost:false,readyGuest:false,updatedAt:serverTimestamp()});else t.update(r,{[field]:true,updatedAt:serverTimestamp()})})}
async sendMessage(text,type="text"){const u=await ensureAuth(),name=this.role==="host"?this.room?.player1?.name:this.role==="guest"?this.room?.player2?.name:"Spectator",clean=String(text||"").trim().slice(0,120);if(!clean)return;await addDoc(collection(db,"rooms",this.code,"messages"),{uid:u.uid,name:sanitizeName(name),text:clean,type,createdAt:serverTimestamp()})}
async touchPresence(){if(!this.code||!["host","guest"].includes(this.role))return;const f=this.role==="host"?"player1.lastSeen":"player2.lastSeen";try{await updateDoc(doc(db,"rooms",this.code),{[f]:serverTimestamp()})}catch{}}
inviteLink(){return`${SITE_URL}?room=${this.code}`}
async leave(){if(!this.code)return;const r=doc(db,"rooms",this.code);try{if(this.role==="spectator")await updateDoc(r,{spectatorCount:increment(-1)})}catch{}this.stop()}
stop(clear=true){this.unsubs.forEach(f=>f());this.unsubs=[];clearInterval(this.heartbeat);this.heartbeat=null;if(clear)localStorage.removeItem(KEY);this.code="";this.role="";this.room=null}}
function playerData(uid,p){return{uid,name:sanitizeName(p.name),color:p.color,lastSeen:serverTimestamp()}}
function clean(v){const c=String(v||"").replace(/\D/g,"").slice(0,6);if(c.length!==6)throw Error("Enter a valid 6-digit room code.");return c}
